In [1]:
# Nami First AI winter school lap cources exposed 
# How to compute Essential matrix using 8 point matrix

In [3]:
# put your dependencies here 
# it called mannners in human language and PEP convention in python language
import numpy as np

In [5]:
p = np.random.uniform(0,1,(50,3))
p

array([[7.90884827e-02, 7.34998193e-01, 2.69812561e-01],
       [1.90235930e-01, 4.38968767e-01, 3.05561699e-02],
       [6.19589912e-01, 8.42898071e-01, 7.58319510e-01],
       [9.17489827e-01, 2.42914837e-02, 3.11307559e-01],
       [4.51927433e-01, 1.06370187e-01, 5.59095332e-05],
       [7.15674651e-01, 8.45984887e-01, 5.53099148e-01],
       [6.12236916e-01, 8.99993807e-01, 3.25502393e-01],
       [2.19354743e-01, 2.07346113e-02, 7.01851956e-01],
       [6.60812987e-02, 1.04642022e-01, 4.62994657e-01],
       [8.98763937e-01, 4.61302254e-01, 4.24948955e-01],
       [6.33910609e-01, 3.09098576e-01, 8.60773092e-01],
       [1.13237672e-01, 4.68923552e-01, 1.52168655e-01],
       [2.52968839e-01, 7.93938614e-01, 2.86944197e-01],
       [7.11697958e-01, 4.26436346e-01, 9.07067406e-01],
       [7.32827491e-01, 7.86168922e-01, 8.32090213e-01],
       [2.69559760e-01, 1.43796592e-01, 1.72122860e-01],
       [8.95048769e-04, 2.71680880e-01, 6.24518650e-01],
       [1.92794105e-01, 5.84612

In [6]:
# Add [ 1 4 3] to all the points -> 1 to x, 4 to y and 3 to z.
b = np.repeat([[1,4,3]],50,axis=0)
b

array([[1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3]])

In [7]:
p = p + b # added [1 4 3] to all the rows in p matrix column wise

In [10]:
o1 = np.ones((50,1),np.float64)
o1

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [11]:
p = np.hstack((p,o1))

In [12]:
p

array([[1.07908848, 4.73499819, 3.26981256, 1.        ],
       [1.19023593, 4.43896877, 3.03055617, 1.        ],
       [1.61958991, 4.84289807, 3.75831951, 1.        ],
       [1.91748983, 4.02429148, 3.31130756, 1.        ],
       [1.45192743, 4.10637019, 3.00005591, 1.        ],
       [1.71567465, 4.84598489, 3.55309915, 1.        ],
       [1.61223692, 4.89999381, 3.32550239, 1.        ],
       [1.21935474, 4.02073461, 3.70185196, 1.        ],
       [1.0660813 , 4.10464202, 3.46299466, 1.        ],
       [1.89876394, 4.46130225, 3.42494895, 1.        ],
       [1.63391061, 4.30909858, 3.86077309, 1.        ],
       [1.11323767, 4.46892355, 3.15216866, 1.        ],
       [1.25296884, 4.79393861, 3.2869442 , 1.        ],
       [1.71169796, 4.42643635, 3.90706741, 1.        ],
       [1.73282749, 4.78616892, 3.83209021, 1.        ],
       [1.26955976, 4.14379659, 3.17212286, 1.        ],
       [1.00089505, 4.27168088, 3.62451865, 1.        ],
       [1.19279411, 4.58461225,

In [18]:
P1 = np.array([ [1,0,0,0], [0,1,0,0], [0,0,1,0]])
q = np.dot(P1, np.transpose(p))
q = np.transpose(q)
u1 = q[:,0]/q[:,2]
v1 = q[:,1]/q[:,2]


In [19]:
q

array([[1.07908848, 4.73499819, 3.26981256],
       [1.19023593, 4.43896877, 3.03055617],
       [1.61958991, 4.84289807, 3.75831951],
       [1.91748983, 4.02429148, 3.31130756],
       [1.45192743, 4.10637019, 3.00005591],
       [1.71567465, 4.84598489, 3.55309915],
       [1.61223692, 4.89999381, 3.32550239],
       [1.21935474, 4.02073461, 3.70185196],
       [1.0660813 , 4.10464202, 3.46299466],
       [1.89876394, 4.46130225, 3.42494895],
       [1.63391061, 4.30909858, 3.86077309],
       [1.11323767, 4.46892355, 3.15216866],
       [1.25296884, 4.79393861, 3.2869442 ],
       [1.71169796, 4.42643635, 3.90706741],
       [1.73282749, 4.78616892, 3.83209021],
       [1.26955976, 4.14379659, 3.17212286],
       [1.00089505, 4.27168088, 3.62451865],
       [1.19279411, 4.58461225, 3.47896206],
       [1.44760424, 4.16818224, 3.6535516 ],
       [1.12748606, 4.48885171, 3.31510767],
       [1.88606353, 4.07192312, 3.59780053],
       [1.38658044, 4.34456845, 3.42432839],
       [1.

In [21]:
R = np.array([[0.8660,0.2500,0.4330],[0,0.8660,-0.500],[-0.500,0.4330,0.7500]])
T = np.array([-0.4,0.4330,0.7500])
# generating position of second camera to the next time 