In [1]:
# Nami First AI winter school lap cources exposed 
# How to compute Essential matrix using 8 point matrix

In [2]:
# put your dependencies here 
# it called mannners in human language and PEP convention in python language
import numpy as np

In [3]:
p = np.random.uniform(0,1,(50,3))
p

array([[5.62501452e-01, 8.67406043e-01, 8.03292887e-01],
       [6.82602394e-01, 9.89940023e-01, 6.45891446e-01],
       [6.88492809e-01, 8.82158795e-01, 1.09453856e-01],
       [6.35949340e-01, 8.56405996e-01, 2.33496836e-01],
       [9.85539374e-01, 4.97216558e-01, 1.65935065e-01],
       [3.79638373e-01, 7.87717107e-01, 2.84020784e-01],
       [2.13798768e-01, 4.76033918e-01, 8.29576898e-01],
       [2.52773414e-01, 9.53876109e-01, 4.15187725e-01],
       [5.63209551e-01, 5.92011406e-04, 4.13820908e-01],
       [3.73272986e-01, 4.65348716e-01, 9.51122647e-01],
       [8.62986293e-01, 4.82406736e-01, 4.90245904e-02],
       [7.78933709e-01, 6.31048462e-01, 9.37438865e-01],
       [2.11035060e-01, 1.57661659e-01, 6.65183748e-01],
       [4.81367323e-01, 8.06470642e-01, 7.58763809e-01],
       [9.75297584e-01, 4.45755207e-01, 6.88715704e-02],
       [4.86783023e-01, 3.64474742e-01, 4.94096712e-01],
       [1.70081927e-01, 2.61375844e-01, 8.54736563e-01],
       [1.50726541e-01, 1.13778

In [5]:
# Add [ 1 4 3] to all the points -> 1 to x, 4 to y and 3 to z.
b = np.repeat([[1,4,3]],50,axis=0)
b

array([[1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3],
       [1, 4, 3]])

In [6]:
p = p + b # added [1 4 3] to all the rows in p matrix column wise

In [7]:
o1 = np.ones((50,1),np.float64)
o1

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [8]:
p = np.hstack((p,o1))

In [9]:
p

array([[1.56250145, 4.86740604, 3.80329289, 1.        ],
       [1.68260239, 4.98994002, 3.64589145, 1.        ],
       [1.68849281, 4.88215879, 3.10945386, 1.        ],
       [1.63594934, 4.856406  , 3.23349684, 1.        ],
       [1.98553937, 4.49721656, 3.16593506, 1.        ],
       [1.37963837, 4.78771711, 3.28402078, 1.        ],
       [1.21379877, 4.47603392, 3.8295769 , 1.        ],
       [1.25277341, 4.95387611, 3.41518772, 1.        ],
       [1.56320955, 4.00059201, 3.41382091, 1.        ],
       [1.37327299, 4.46534872, 3.95112265, 1.        ],
       [1.86298629, 4.48240674, 3.04902459, 1.        ],
       [1.77893371, 4.63104846, 3.93743886, 1.        ],
       [1.21103506, 4.15766166, 3.66518375, 1.        ],
       [1.48136732, 4.80647064, 3.75876381, 1.        ],
       [1.97529758, 4.44575521, 3.06887157, 1.        ],
       [1.48678302, 4.36447474, 3.49409671, 1.        ],
       [1.17008193, 4.26137584, 3.85473656, 1.        ],
       [1.15072654, 4.11377883,

In [10]:
P1 = np.array([ [1,0,0,0], [0,1,0,0], [0,0,1,0]])
q = np.dot(P1, np.transpose(p))
q = np.transpose(q)
u1 = q[:,0]/q[:,2]
v1 = q[:,1]/q[:,2]


In [11]:
q

array([[1.56250145, 4.86740604, 3.80329289],
       [1.68260239, 4.98994002, 3.64589145],
       [1.68849281, 4.88215879, 3.10945386],
       [1.63594934, 4.856406  , 3.23349684],
       [1.98553937, 4.49721656, 3.16593506],
       [1.37963837, 4.78771711, 3.28402078],
       [1.21379877, 4.47603392, 3.8295769 ],
       [1.25277341, 4.95387611, 3.41518772],
       [1.56320955, 4.00059201, 3.41382091],
       [1.37327299, 4.46534872, 3.95112265],
       [1.86298629, 4.48240674, 3.04902459],
       [1.77893371, 4.63104846, 3.93743886],
       [1.21103506, 4.15766166, 3.66518375],
       [1.48136732, 4.80647064, 3.75876381],
       [1.97529758, 4.44575521, 3.06887157],
       [1.48678302, 4.36447474, 3.49409671],
       [1.17008193, 4.26137584, 3.85473656],
       [1.15072654, 4.11377883, 3.64399009],
       [1.4210556 , 4.36992233, 3.72262731],
       [1.65755946, 4.15905758, 3.53546964],
       [1.55652107, 4.33183927, 3.92056232],
       [1.27919812, 4.40224477, 3.98207954],
       [1.

In [16]:
R = np.array([[0.8660,0.2500,0.4330],[0,0.8660,-0.500],[-0.500,0.4330,0.7500]])
T = np.array([[-0.4],[0.4330],[0.7500]])
# generating position of second camera to the next time 

In [17]:
np.hstack((R,T))

array([[ 0.866,  0.25 ,  0.433, -0.4  ],
       [ 0.   ,  0.866, -0.5  ,  0.433],
       [-0.5  ,  0.433,  0.75 ,  0.75 ]])

In [18]:
P2 = np.hstack((R,T))

In [19]:
q2 = np.dot(P2, np.transpose(p))
q2 = np.transpose(q2)
u2 = q2[:,0]/q2[:,2]
v2 = q2[:,1]/q2[:,2]

In [20]:
# Now comute the the A matrix or 8 point matrix to solve 8 point  equation
A = [u2 * u1,  u2 * v1 , u2 , v2 * u1 , v2 * v1 , v2 , u1 , v1 , 1]

In [21]:
A

[array([0.31814036, 0.37307498, 0.45284687, 0.41189271, 0.58651329,
        0.31201504, 0.21937091, 0.25838124, 0.36882432, 0.25340597,
        0.55181735, 0.37532931, 0.23056253, 0.2979775 , 0.60522898,
        0.32891924, 0.20733445, 0.21570347, 0.28567852, 0.38655173,
        0.3091731 , 0.22681865, 0.34126458, 0.5223674 , 0.24603642,
        0.60405657, 0.28333545, 0.49104928, 0.22980248, 0.24294233,
        0.4623588 , 0.21053073, 0.59985655, 0.46466623, 0.45507346,
        0.23742803, 0.29246144, 0.34312686, 0.23851657, 0.25456226,
        0.4900107 , 0.32016493, 0.18298891, 0.2037255 , 0.25296445,
        0.34017617, 0.29979564, 0.27751836, 0.49473578, 0.39326596]),
 array([0.9910508 , 1.10639435, 1.30937504, 1.22272627, 1.3284437 ,
        1.08277631, 0.8089575 , 1.02172401, 0.94390137, 0.82397747,
        1.32769084, 0.97708432, 0.79155512, 0.96682309, 1.36217444,
        0.96554755, 0.75510097, 0.77112706, 0.87849689, 0.96991448,
        0.86043691, 0.78057589, 0.90729513, 1.

In [22]:
#  Formulate two equations:
# Solve Ax = 0
# and Ax = 0 and Ax = b
u, s, vh = np.linalg.svd(A, full_matrices=True)


LinAlgError: 1-dimensional array given. Array must be at least two-dimensional